### ISSUE TITLE
support optional properties

### ISSUE THREAD

**Issue by fateme3** [Bwca/property-string-path#2]
the package doesn't support optional properties and doesn't show the properties of an optional propery..!!?!

**Comment by Bwca** [comment]
That's correct.

**Comment by Bwca** [comment]
I better add explanation: originally the package was designed to help with paths to controls in forms (React or Angular), which means given paths were always leading to a control, furthermore, a `?.` would render the path invalid if used with Angular forms or HookForm (this one I didn't test, it's my assumption).
